[package]
name = "apollo-composition"
version = "0.1.3"
license = "Elastic-2.0"
edition = "2021"
authors = ["Apollo Developers <opensource@apollographql.com>"]
description = "Internal package used to create Apollo products"
readme = "README.md"
repository = "https://github.com/apollographql/federation-rs/"

[dependencies]
apollo-compiler = "1.0.0-beta.24"
# TODO: Switch to published apollo-federation before release
apollo-federation = { version = "2.0.0-alpha.7", git = "https://github.com/apollographql/router", branch = "next" }
apollo-federation-types = { version = "0.14.0", path = "../apollo-federation-types" }
either = "1.12.0"
